name: Create Changelog

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Create Changelog
        id: create_changelog
        run: |
          npm install -g standard-version
          npm run release -- --skip.tag --skip.commit
          git add CHANGELOG.md
          git checkout -- package.json
          version=$(cat CHANGELOG.md | grep -o -E '[0-9]+\.[0-9]+\.[0-9]' | sed -n '1p')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Read changelog
        uses: mathiasvr/command-output@v1
        id: changelog_data
        with:
          run: cat CHANGELOG.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(changelog): update CHANGELOG.md for v${{ steps.create_changelog.outputs.version }}"
          branch: changelog
          delete-branch: true
          title: 'Changelog v${{ steps.create_changelog.outputs.version }}'
          body: ${{ steps.changelog_data.outputs.stdout }}
          assignees: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>